[package]
name = "bioengineer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"
futures = "0.3"
opensimplex_noise_rs = "0.3.0"
