name: Build and test

on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install system dependencies
      run: sudo apt-get install libx11-dev libxi-dev libgl1-mesa-dev gcc-mingw-w64 libasound2-dev
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test
