name: Build and test in Mac

on:
  # workflow_dispatch will enable manual triggers
  workflow_dispatch:

  # I disabled automatic builds because I often just push when I tag, and every commit was
  # being built twice
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose --bin bioengineer

      - name: Run tests
        run: cargo test
