name: Build and test

on:
  workflow_dispatch:
  

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test
