name: Build and test in Linux

on:
  # workflow_dispatch will enable manual triggers
  workflow_dispatch:

  # I disabled automatic builds because I often just push when I tag, and every commit was
  # being built twice
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
  

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # force downloading all tags so that git_version! works
          fetch-depth: 0

      - name: Install system dependencies
        run: sudo apt-get install libx11-dev libxi-dev libgl1-mesa-dev gcc-mingw-w64 libasound2-dev

      - name: Build
        run: cargo build --verbose --bin bioengineer

      - name: Run tests
        run: cargo test
